### ISSUE TITLE
can't load package 

### ISSUE THREAD

**Issue by darshik** [cycloidio/goat#12]
go get github.com/cycloidio/goat throws the following error:
can't load package: package github.com/cycloidio/goat: no buildable Go source files in /Users/darshik/go/src/github.com/cycloidio/goat

**Comment by xlr-8** [comment]
indeed the repository containing a subdir, you should try:

```bash
go get github.com/cycloidio/goat/auth0
``` 
That should work better, the README will be fixed accordingly

**Comment by XescuGC** [comment]
There is another way to do it, with the `go get github.com/cycloidio/goat/auth0/...`

From the `go help packages`

```
[...]
An import path is a pattern if it includes one or more "..." wildcards,
each of which can match any string, including the empty string and
strings containing slashes.  Such a pattern expands to all package
directories found in the GOPATH trees with names matching the
patterns.  As a special case, x/... matches x as well as x's subdirectories.
For example, net/... expands to net and packages in its subdirectories.
[...]
```

We could just add this to the documentation :)

**Comment by XescuGC** [comment]
Review at #13
