### ISSUE TITLE
GetUser method should handle params

### ISSUE THREAD

**Issue by Seraf** [cycloidio/goat#8]
Hello,

On auth0 API specs, there's some fields to pass through the params to return a subset of users : https://auth0.com/docs/api/management/v2#!/Users/get_users

The GetUser method should handle an optional params map to be able to filter the users returned

**Comment by xlr-8** [comment]
The `GetUsers` method already take a params variable: https://github.com/cycloidio/goat/blob/develop/auth0/users.go#L30-L32

**Comment by xlr-8** [comment]
I think indeed the `BuildParamsURL` function is incorrect, I think it should looks like something like this:
```go
-	for _, val := range params {
-	    params_url += "?" + val
+	for key, val := range params {
+		params_url += "?" + key + "=" + val
```
